// liclem97 All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace CombatGameplayTags
{
	/** Input Tags **/
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipRifle);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipRifle);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Fire_Rifle);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim_Rifle);

	/** Player Tags **/
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Rifle);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Rifle);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);

	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Rifle);

	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unquip_Axe);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Rifle);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unquip_Rifle);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);

	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_AimRifle);

	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	/** Enemy Tags **/
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	/** Shared Tags **/
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);

	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);

	COMBATRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);
}